module UV
  class Error < StandardError
    class UNKNOWN < Error; end
    class OK < Error; end
    class EOF < Error; end
    class EADDRINFO < Error; end
    class EACCES < Error; end
    class EAGAIN < Error; end
    class EADDRINUSE < Error; end
    class EADDRNOTAVAIL < Error; end
    class EAFNOSUPPORT < Error; end
    class EALREADY < Error; end
    class EBADF < Error; end
    class EBUSY < Error; end
    class ECONNABORTED < Error; end
    class ECONNREFUSED < Error; end
    class ECONNRESET < Error; end
    class EDESTADDRREQ < Error; end
    class EFAULT < Error; end
    class EHOSTUNREACH < Error; end
    class EINTR < Error; end
    class EINVAL < Error; end
    class EISCONN < Error; end
    class EMFILE < Error; end
    class EMSGSIZE < Error; end
    class ENETDOWN < Error; end
    class ENETUNREACH < Error; end
    class ENFILE < Error; end
    class ENOBUFS < Error; end
    class ENOMEM < Error; end
    class ENOTDIR < Error; end
    class EISDIR < Error; end
    class ENONET < Error; end
    class ENOTCONN < Error; end
    class ENOTSOCK < Error; end
    class ENOTSUP < Error; end
    class ENOENT < Error; end
    class ENOSYS < Error; end
    class EPIPE < Error; end
    class EPROTO < Error; end
    class EPROTONOSUPPORT < Error; end
    class EPROTOTYPE < Error; end
    class ETIMEDOUT < Error; end
    class ECHARSE < Error; end
    class EAIFAMNOSUPPORT < Error; end
    class EAISERVICE < Error; end
    class EAISOCKTYPE < Error; end
    class ESHUTDOWN < Error; end
    class EEXIST < Error; end
    class ESRCH < Error; end
    class ENAMETOOLONG < Error; end
    class EPERM < Error; end
    class ELOOP < Error; end
    class EXDEV < Error; end
    class ENOTEMPTY < Error; end
    class ENOSPC < Error; end
  end
end
